{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sb",
    "module": "ivy-publish-test-fixtures",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ivy-publish-test-fixtures-1.0.0.jar",
          "url": "ivy-publish-test-fixtures-1.0.0.jar",
          "size": 996,
          "sha512": "ff219e88755b4aa94110cb01e28a1beda84fec523a7022db4672fc751e4ee9130f1c5751c0f3c6338ed91dbbb26fabd811cace6833bda727a69224063ebbce56",
          "sha256": "2a14da8c55954ce66040f3dc1f0035811a8be7baaf22136a9b4905d22806a596",
          "sha1": "2d1d2899aa23649c5cbb114f6b798448f2bc41fd",
          "md5": "29a224cfa159c1d2fbc0792f5cc90ee6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ivy-publish-test-fixtures-1.0.0.jar",
          "url": "ivy-publish-test-fixtures-1.0.0.jar",
          "size": 996,
          "sha512": "ff219e88755b4aa94110cb01e28a1beda84fec523a7022db4672fc751e4ee9130f1c5751c0f3c6338ed91dbbb26fabd811cace6833bda727a69224063ebbce56",
          "sha256": "2a14da8c55954ce66040f3dc1f0035811a8be7baaf22136a9b4905d22806a596",
          "sha1": "2d1d2899aa23649c5cbb114f6b798448f2bc41fd",
          "md5": "29a224cfa159c1d2fbc0792f5cc90ee6"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.sb",
          "module": "ivy-publish-test-fixtures",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ivy-publish-test-fixtures-1.0.0-test-fixtures.jar",
          "url": "ivy-publish-test-fixtures-1.0.0-test-fixtures.jar",
          "size": 798,
          "sha512": "fc7ed0de9e59ca3a6a0c3f24a7b8b08e759fd2554e97eeefd34a8fec5633d38031f9e4aee42a816228f8b9d3be2cd5790a3d5c19509324d8a331d66ec792eaf6",
          "sha256": "30e47d97fd5a9048ca67ef8b0aca04499ed4f4afd87868de83eee8f3150d77ed",
          "sha1": "7247c4bbf25233ceec71cc3d8d1b2055a400bc83",
          "md5": "c215496e7df37a29b924729a62862c93"
        }
      ],
      "capabilities": [
        {
          "group": "com.sb",
          "name": "ivy-publish-test-fixtures-test-fixtures",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.sb",
          "module": "ivy-publish-test-fixtures",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ivy-publish-test-fixtures-1.0.0-test-fixtures.jar",
          "url": "ivy-publish-test-fixtures-1.0.0-test-fixtures.jar",
          "size": 798,
          "sha512": "fc7ed0de9e59ca3a6a0c3f24a7b8b08e759fd2554e97eeefd34a8fec5633d38031f9e4aee42a816228f8b9d3be2cd5790a3d5c19509324d8a331d66ec792eaf6",
          "sha256": "30e47d97fd5a9048ca67ef8b0aca04499ed4f4afd87868de83eee8f3150d77ed",
          "sha1": "7247c4bbf25233ceec71cc3d8d1b2055a400bc83",
          "md5": "c215496e7df37a29b924729a62862c93"
        }
      ],
      "capabilities": [
        {
          "group": "com.sb",
          "name": "ivy-publish-test-fixtures-test-fixtures",
          "version": "1.0.0"
        }
      ]
    }
  ]
}
